<?php 
return [
'cnf_appname' 			=> 'Sximo 5.1.8',
'cnf_appdesc' 			=> 'PHP Application Builder',
'cnf_comname' 			=> 'Sximo5',
'cnf_email' 			=> 'info@mycompanyname.com',
'cnf_metakey' 			=> 'my site , my company  , Larvel Crud',
'cnf_metadesc' 		=> 'Write description for your site',
'cnf_group' 			=> '3',
'cnf_activation' 		=> 'confirmation',
'cnf_multilang' 		=> '1',
'cnf_lang' 			=> 'ru',
'cnf_regist' 			=> 'true',
'cnf_front' 			=> 'true',
'cnf_recaptcha' 		=> 'false',
'cnf_theme' 			=> 'sailor',
'cnf_recaptchapublickey' => '',
'cnf_recaptchaprivatekey' => '',
'cnf_mode' 			=> 'production',
'cnf_logo' 			=> 'logo-light.png',
'cnf_allowip' 			=> '',
'cnf_restrictip' 		=> '192.116.134 , 194.111.606.21 ',
'cnf_mail' 			=> 'swift',
'cnf_date' 			=> 'Y-m-d',
];
